module OsvrCompatibilityAggregator
end

require 'osvr_compatibility_aggregator/version'
require 'osvr_compatibility_aggregator/device_descriptors'
require 'osvr_compatibility_aggregator/display_descriptors'
